**Deadline**: 30.10.2024 19:00 (GMT+3)

## Part I: Implement 2048 environment (6 points)

In this homework our goal is implement and solve [2048 game](https://en.wikipedia.org/wiki/2048_(video_game)). If you are not familiar with it, it's highly recommended to play some games (e.g. [here](https://2048game.com/)).

One of the most interesting question that you probably will ask yourself during solving this task is "How to design reward function here?". You can use the [reward function from the origin game](https://en.wikipedia.org/wiki/2048_(video_game)#:~:text=The%20user's%20score%20starts%20at,that%20to%20reach%20higher%20scores.) or you can use it as inspiration for developing your own reward function. Think about what is "good" reward function in this context. 

Implementation **must be consistent** with gymnasium interfaces. Keep in mind that all tests passed is requirement for achiving non-zero score for this task.

Below you can find tests that may help you with implementation.

In [10]:
%load_ext autoreload
%autoreload 2

import numpy as np
from env import Game2048Env

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:
env = Game2048Env(render_mode='ansi')
print(env.render())

Score: 0
Highest: 2
[[0 2 0 0]
 [0 0 0 2]
 [0 0 0 0]
 [0 0 0 0]]



In [12]:
assert env.get_board().shape == (4, 4)

In [28]:
test_left = np.array([[2, 0, 2, 4], [2, 2, 2, 2], [4, 8, 0, 16], [8, 16, 4, 0]])
answer = np.array([[4, 4, 0, 0], [4, 4, 0, 0], [4, 8, 16, 0], [8, 16, 4, 0]])

env.set_board(test_left)
score = env.move(3)
assert np.allclose(env.get_board(), answer)
assert np.allclose(score, 12)

## Part II: Implement CEM (4 points)

In this task, your goal is to train the CEM algorithm to solve your own environment. Try any tricks you learned in the webinars. You will solve the task if your solution can reach 1024 as a max tile.